vim.cmd.colorscheme("rose-pine-main")
vim.api.nvim_set_hl(0, "Normal", { bg = "NONE", ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "NONE", ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "SignColumn", { bg = "NONE", ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "LineNr", { bg = "NONE", fg = "#7f7f7f" })
vim.api.nvim_set_hl(0, "EndOfBuffer", { bg = "NONE", ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "NONE", ctermbg = "NONE" })
vim.api.nvim_set_hl(0, "TelescopeNormal", { bg = "NONE", link = "Normal" })
vim.api.nvim_set_hl(0, "TelescopePromptNormal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "TelescopeResultsNormal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "TelescopePreviewNormal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "TelescopeBorder", { bg = "NONE", link = "Comment" })
vim.api.nvim_set_hl(0, "TelescopePromptBorder", { bg = "NONE", link = "Comment" })
vim.api.nvim_set_hl(0, "TelescopeResultsBorder", { bg = "NONE", link = "Comment" })
vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { bg = "NONE", link = "Comment" })
vim.api.nvim_set_hl(0, "OilDir", { link = "Directory" })
vim.api.nvim_set_hl(0, "BufferTabpageFill", { bg = "NONE", link = "Normal" })
vim.api.nvim_set_hl(0, "BufferCurrent", { bg = "NONE", fg = "#ffffff", bold = true })
vim.api.nvim_set_hl(0, "BufferVisible", { bg = "NONE", fg = "#aaaaaa" })
vim.api.nvim_set_hl(0, "BufferInactive", { bg = "NONE", fg = "#7f7f7f" })
vim.api.nvim_set_hl(0, "BufferCurrentMod", { bg = "NONE", link = "BufferCurrent" })
vim.api.nvim_set_hl(0, "BufferVisibleMod", { bg = "NONE", link = "BufferVisible" })
vim.api.nvim_set_hl(0, "BufferInactiveMod", { bg = "NONE", link = "BufferInactive", italic = true })
vim.api.nvim_set_hl(0, "BufferTabpages", { bg = "NONE" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { link = "ErrorMsg" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { link = "WarningMsg" })
vim.api.nvim_set_hl(0, "TroubleNormal", { bg = "NONE", link = "Normal" })
